### ISSUE TITLE
Document mixing and matching better.

### ISSUE THREAD

**Issue by jonhoo** [crate-ci/azure-pipelines#3]
See [this Reddit answer](https://www.reddit.com/r/rust/comments/cc4k9x/rustypipes_easy_continuous_integration_for_rust/etm8xim/) for example. Pointing out how users can do things like
```yaml
 - stage: feature-check
   jobs:
    - job: feature-check
      displayName: cargo check --features XYZ
      pool:
        vmImage: ubuntu-16.04
      steps:
       - template: azure/install-rust.yml@templates
       - script: cargo check --features xyz
         displayName: Run cargo check w/ XYZ
```
Somewhere that's easy to find is probably a good idea! This will likely go along with finding a better way to structure the README.
