### ISSUE TITLE
Provide convention over configuration route

### ISSUE THREAD

**Issue by nickbabcock** [crate-ci/azure-pipelines#7]
Given a config of

```yml
strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta
steps:
  - template: rustup.yml
    parameters:
      rustup_toolchain: $(rustup_toolchain)
```

Listing the rustup_toolchain parameter seems redundant (one has to type out "rustup_toolchain" 3 times). I've played around with the following convention in some templates: 

> 1. Use parameter if provided
> 2. Global RUSTUP_TOOLCHAIN if available
> 3. Default to stable if none are available

By relying on this global variable, we condense the config (and if subsequent templates relied on that parameter, the savings would be even greater). Resulting in:

```yaml
strategy:
  matrix:
    stable:
      rustup_toolchain: stable
    beta:
      rustup_toolchain: beta
steps:
  - template: rustup.yml
```

These global variables can be documented. There are of course downsides to this approach (a breaking change in the variable name may go undetected, but maybe there will be template versions like tasks (self-imposed version maybe like `rustup-1.yml` or `rustup-2.yml` 🤔 )).
