### ISSUE TITLE
Run fails with "/default.yml@templates (Line: 8, Col: 1): Unexpected value 'jobs'"

### ISSUE THREAD

**Issue by 1wilkens** [crate-ci/azure-pipelines#75]
I recently migrated(?) my CI from the old path (`azure/stages.yml`) to the new `default.yml` but now I get the following error when running the azure pipeline:
`/default.yml@templates (Line: 8, Col: 1): Unexpected value 'jobs'`

My `azure-pipelines.yml` is [here](https://github.com/1wilkens/pam-sys/blob/master/azure-pipelines.yml) and the failed build can be seen [here](https://dev.azure.com/1wilkens/ci/_build/results?buildId=19&view=results/default.yml@templates).

Did I forgot to change something when migrating or do you have any other idea why this build fails?

**Comment by epage** [comment]
Something that isn't obvious is the pipeline changed from providing stages to providing jobs, so you need to change the hierarchy above the template reference.

I made this mistake after updating all of my repos.  See https://github.com/assert-rs/assert_fs/commit/c061349c910a0fe73526c15bd38ff515f452151b#diff-fec826feae04e51c0d94076385408bdc for an example of the fix.

Also, in case you weren't aware, we updated our instructions for versioned releases so you don't get surprised by breaking changes
(I still need to switch to this)

```yaml
resources:
  repositories:
    - repository: templates
      type: github
      name: crate-ci/azure-pipelines
      ref: refs/heads/v0.3
      endpoint: YOU_NEED_TO_SET_THIS
```
See the `ref` part
